### ISSUE TITLE
Ajax call /?wc-ajax=get_refreshed_fragments clears cart when plugin installed

### ISSUE THREAD

**Issue by pristas-peter** [wp-graphql/wp-graphql-woocommerce#143]
I have installed vanilla Woocommerce with Storefront theme and this plugin with wp-graphql.

When I click add to cart the product is added to the cart and page refreshed with correct items in cart. However on page load there is an ajax call `/?wc-ajax=get_refreshed_fragments`. Response from that cart clears cart_hash cookie and returns 0 products in cart.

This does not happen when plugin is deactivated.

**Screenshots**
<img width="993" alt="Screenshot 2019-09-25 at 08 12 35" src="https://user-images.githubusercontent.com/9489687/65573980-7857e900-df6c-11e9-9f9f-87bab283401d.png">

**Comment by kidunot89** [comment]
The is most likely due to the **[QL_Session_Handler](https://github.com/wp-graphql/wp-graphql-woocommerce/blob/develop/includes/utils/class-ql-session-handler.php)**. Sounds like it's preventing the woocommerce session cookie from being updated property. This is definitely a bug, since the **QL_Session_Handler** shouldn't be used on non-GraphQL request. :thinking:

**Comment by kidunot89** [comment]
Fixed in #146

**Comment by kidunot89** [comment]
Fixed in #146. @pristas-peter thanks for catching this one. It would have been a pain down the line.
