### ISSUE TITLE
Need `transactionId` for checkout mutation

### ISSUE THREAD

**Issue by Nisfan** [wp-graphql/wp-graphql-woocommerce#226]
We need to inform woocommerce about the payment made via stripe

**Comment by kidunot89** [comment]
To elaborate more on this when an order is created using the `createOrder` or `checkout` the order payment status is check using a transaction ID typically distributed when the payment service processing the payment. Upon the checking of this token the order `status` is set. The `transactionId` isn't required to execute either mutation, however the problem is that it's currently not possible to pass the `transactionId` to the `checkout` mutation as an argument.
