### ISSUE TITLE
Problem with union query on some products.

### ISSUE THREAD

**Issue by dksami** [wp-graphql/wp-graphql-woocommerce#227]
**Describe the bug**
So i have just found a bug in the plugin, the union query is not working as it should be, Some of the products from normal products query with union to simple products have nothing in the simple product object and returning nothing.

**To Reproduce**
https://eproject.tk/graphql
```
query getProducts{
  products(first: 15, ){
    nodes {
   	name
      id
      ... on SimpleProduct{
        price
        onSale
      }
      }
    }
  }

```

**Expected behavior**
All product should get a result from simple product union

**Screenshots**
https://imgur.com/IVfJUyE

**Comment by kidunot89** [comment]
@dksami Can you show me some example query results?

**Comment by dksami** [comment]
YOU CAn USE THAT QUERY ABOVE THAT I SEND YOU TO YOUR GRAPHQL, AND YOU WILL NOTICE.

**Comment by kidunot89** [comment]
@dksami No need to yell :expressionless: , I asked because I'm not getting an error running that query. So I can't recreate the issue, and I'm gonna need more information if you wish to resolve the issue.
![image](https://user-images.githubusercontent.com/13604318/73659033-69441e80-4663-11ea-9d7a-61a63f8e7155.png)

**Comment by kidunot89** [comment]
Sorry, I was misreading your issue, this is not a bug. Run this query and you should see whats happening.
```
query getProducts {
  products(first: 15) {
    nodes {
      name
      id
      type
      ... on SimpleProduct {
        price
        onSale
      }
    }
  }
}
```
The result won't restricted to simple products just because you only request `SimpleProduct` in the output. To filter the results you have to use the `whereArgs` here's an example that should give you what you want.
```
query getProducts {
  products(first: 15, where: {type: SIMPLE}) {
    nodes {
      name
      id
      ... on SimpleProduct {
        price
        onSale
      }
    }
  }
}
```

**Comment by dksami** [comment]
so you are saying that the products that don't have the pricing on are not simple products, so let's suppose if I want to fetch em all, how can I?
