### ISSUE TITLE
Orderby argument not working

### ISSUE THREAD

**Issue by HiepVu511** [wp-graphql/wp-graphql-woocommerce#262]
**Describe the bug**
Multiple sorting types with `orderby` argument are not working. Only the last type is processed.

**To Reproduce**
Here I use 2 sorting types `MENU_ORDER` and `DATE`:
```
query MyQuery {
  __typename
  products(where: {orderby: [{field: MENU_ORDER}, {field: DATE}]}) {
    edges {
      node {
        name
        date
        menuOrder
      }
    }
  }
}
```

**Expected behavior**
Products should be order by both `DATE` and `MENU_ORDER`

**Actual behavior**
Only `DATE` sorting type was processed
![image](https://user-images.githubusercontent.com/13346949/79849481-bd51da00-83ec-11ea-8bd2-d2e8077d2de0.png)

**Comment by kidunot89** [comment]
@HiepVu511 I don't think is a bug. It looks like it's working in reverse :thinking: . The last item in the `orderBy` array maybe getting processed first.

**Comment by paplco** [comment]
Yes, seems the last item takes precedence. All of the dates are in order. Would need to use equal dates for the menu order to take effect in this case.

**Comment by loganstellway** [comment]
I am running into issues with this as well.
It looks like the issue resides in [`WC_CPT_Loader_Common:: sanitize_common_inputs ()`](https://github.com/wp-graphql/wp-graphql-woocommerce/blob/f5f3de1de86988c2acc6a4ade76ec872fc8c75df/includes/data/connection/trait-wc-cpt-loader-common.php#L43).

The logic creates an [`orderby` array](https://github.com/wp-graphql/wp-graphql-woocommerce/blob/f5f3de1de86988c2acc6a4ade76ec872fc8c75df/includes/data/connection/trait-wc-cpt-loader-common.php#L76), but the following loop completely [overrides the array](https://github.com/wp-graphql/wp-graphql-woocommerce/blob/f5f3de1de86988c2acc6a4ade76ec872fc8c75df/includes/data/connection/trait-wc-cpt-loader-common.php#L86-L97) instead of appending to it. 

I'm not sure if this is intentional, but I know WordPress supports using multiple order by ([reference](https://developer.wordpress.org/reference/classes/wp_query/#order-orderby-parameters)).

**Comment by loganstellway** [comment]
Here's a patch in case anyone wants a temporary fix:
```
diff --git a/includes/data/connection/trait-wc-cpt-loader-common.php b/includes/data/connection/trait-wc-cpt-loader-common.php
index f3d883d..824dd89 100644
--- a/includes/data/connection/trait-wc-cpt-loader-common.php
+++ b/includes/data/connection/trait-wc-cpt-loader-common.php
@@ -87,14 +87,12 @@ trait WC_CPT_Loader_Common {
 
 					// Handle meta fields.
 				} elseif ( in_array( $orderby_input['field'], $this->ordering_meta(), true ) ) {
-					$args['orderby']  = array( 'meta_value_num' => $orderby_input['order'] );
-					$args['meta_key'] = esc_sql( $orderby_input['field'] ); // WPCS: slow query ok.
+					$args['orderby']['meta_value_num'] = $orderby_input['order'];
+					$args['meta_key']  = esc_sql( $orderby_input['field'] ); // WPCS: slow query ok.
 
 					// Handle post object fields.
 				} elseif ( ! empty( $orderby_input['field'] ) ) {
-					$args['orderby'] = array(
-						esc_sql( $orderby_input['field'] ) => esc_sql( $orderby_input['order'] ),
-					);
+					$args['orderby'][esc_sql( $orderby_input['field'] )] = esc_sql( $orderby_input['order'] );
 				}
 			}
 		}
```
_(If you're using composer, you can include the patch with [cweagans/composer-patches](https://github.com/cweagans/composer-patches))_
