### ISSUE TITLE
Return updated product inventory in addToCart mutation

### ISSUE THREAD

**Issue by thetre97** [wp-graphql/wp-graphql-woocommerce#307]
**Is your feature request related to a problem? Please describe.**

I understood that with WooCommerce, if a customer adds a product to cart, it will optimistically decrease the available stock quantity for that product for a certain period while it is in the cart. This request is based on that assumption, so please correct me if I am wrong.

When a product page is visited, I fetch the current inventory status for that product. The `max` value of the quantity input is set to the `stockQuantity` value. When an `addToCart` mutation is then run, I tried to use the returned product in that mutation to update the Apollo store for that product, so I didn't have to refetch the product inventory again to decrease the `stockQuantity` available (I.e. there are `3` of an item left, the customer adds all 3 to cart, so the available qty should now show as out of stock`).

However, that product under `cartItem` returns the `stockQuantity` originally available, rather than the updated quantity taking into account the amount just added to cart.

```graphql
addToCart (input: $input) {
	cart {
      ...
    }
    cartItem {
      ...
	  product {
	    id
	    name
	    ... on SimpleProduct {
		    stockStatus
		    stockQuantity
		    backordersAllowed
		  }
		  ... on VariableProduct {
		    variations {
		      nodes {
		        id
		        sku
		        stockStatus
		        stockQuantity
		      }
		    }
		  }
	  }
	  ...
	}
}
```

**Describe the solution you'd like**
Ideally, the `cartItem { product` would return the updated inventory status.

**Describe alternatives you've considered**
The alternative is just optimistically updating the store manually, so do `updatedQuantity = stockQuantity - 3` etc.

**Comment by kidunot89** [comment]
@thetre97 As far as I know, WooCommerce does not optimistically update the product's stock quantity upon adding it to the cart. This is done when an upon order creation. WooCommerce simply checks the stock quantity, before putting it in the cart.

If I am wrong, and WooCommerce does update the product's stock quantity or a external Woo extension is doing it, and the `stockQuantity` isn't updated in the response. It's probably because the stock quantity is being updated at the end of the request in the `shutdown` action, meaning you have to do a second request for the updated product stock quantity. 

But as I say before, as far as I know, WooCommerce does not optimistically update the product's stock quantity upon adding it to the cart.

**Comment by thetre97** [comment]
@kidunot89 Just dug into the docs a bit more, and you are correct, it will only hold stock while a user is at the order payment stage.

Thanks anyway for this great plugin! 👍
