### ISSUE TITLE
Gatsby: occured while fetching nodes of the "PaQuantity"

### ISSUE THREAD

**Issue by magicspon** [wp-graphql/wp-graphql-woocommerce#354]
**Describe the bug**

When I boot up gatsby I get the following error:

```
success  gatsby-source-wordpress  VisibleProduct - 18.136s - fetched 9
info  gatsby-source-wordpress  GraphQL vars: {"first":100,"url":"http://mysite.test/wp/graphql","after":null}
error  gatsby-source-wordpress  Request failed with status code 500

Error occured while fetching nodes of the "PaQuantity" type.

GraphQL request to http://mysite.test/wp/graphql failed.

Please ensure the following statements are true
  - your WordPress URL is correct in gatsby-config.js
  - your server is responding to requests
  - WPGraphQL and WPGatsby are installed in your WordPress backend
not finished source and transform nodes - 76.843s
not finished  gatsby-source-wordpress  fetching nodes - 76.808s - 37 total
not finished  gatsby-source-wordpress  PaQuantity - 76.804s
not finished  gatsby-source-wordpress  Product - 76.802s
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! oomph-site@2.0.0 dev: `gatsby develop -H 0.0.0.0 --port 3000`
npm ERR! Exit status 1
```

**To Reproduce**
1. Create an attribute, with 17 terms
2. Create a few variable products, with all of the attributes set to variants
3. Start gatsby

**Expected behavior**
Gatsby starts up.

Latest OS, latest version of all the things
node 12.19.0

**Comment by ardiewen** [comment]
Please look at the `gatsby-source-wordpress-experimental` [documentation](https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/blob/master/docs/debugging-and-troubleshooting.md#wordpress-50-errors) with regards to 500 codes, and see if that resolves your issue.

I've experienced this issue with some wordpress hosts, with different errors (500, 504), but the fix is almost always one (or a combination of) of the following:

1. lower the value of `schema.perPage` plugin option
2. lower the value of `GATSBY_CONCURRENT_DOWNLOAD` env variable
3. increase the value of `WP_MEMORY_LIMIT` in wp-config
4. check your host's logs (if hosted wp) to see if there's anything environment specific

Related issues on the main repo:
https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/issues/85
https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/issues/143
https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/issues/201

**Comment by kidunot89** [comment]
@magicspon Is this still an issue? Sorry for the late response.

**Comment by magicspon** [comment]
@kidunot89 I'm no longer using wordpress/woocommerce, so I'm not sure.

**Comment by kidunot89** [comment]
Then I'll close this
