### ISSUE TITLE
paymentGateways node is not available to query

### ISSUE THREAD

**Issue by MobyDigg** [wp-graphql/wp-graphql-woocommerce#388]
I can see ``paymentGateways`` in the GraphiQL editor in the WordPress backend, but once I try to query them locally or in production the respective node ``wpPaymentGateways`` is not available. What am I doing wrong?

**Comment by kidunot89** [comment]
@MobyDigg Do you have the payment gateways enabled in the WooCommerce settings?

**Comment by MobyDigg** [comment]
@kidunot89 yes, I have several activated in the WooCommerce settings and I can query them accordingly through GraphiQL through the WordPress backend, but not through my app… There it doesn't appear on ``http://localhost:8000/__graphql`` at all…

**Comment by MobyDigg** [comment]
@kidunot89 I also noticed, that I get the following warning, once I use ``gatsby clean`` and restart yarn dev:

```
warn  gatsby-source-wordpress  Unable to find a single Node query for PaymentGateway
        This type will not be available in Gatsby.
```

**Comment by MobyDigg** [comment]
@kidunot89 any idea, what this could be?

**Comment by kidunot89** [comment]
Do you have any payment gateway installed and enabled?

**Comment by MobyDigg** [comment]
> @MobyDigg Do you have any payment gateway installed and enabled?

Yes, I have several installed and enabled. As mentioned above, they appear in the backend in GraphiQL but NOT in the frontend.

**Comment by kidunot89** [comment]
This is probably because the unique nature of the PaymentGateway data object.

**Comment by TylerBarnes** [comment]
Hey there 👋 this is because the Gatsby source plugin has a hard requirement that any nodes that are sourced have both a root field that can fetch a list of nodes as well as an individual node. We need the list entry point to pull all nodes during cold builds and the single entry point so we can make delta updates on individual nodes on warm cache builds. 

Depending on how dynamic this node type is, you might not want to source it into Gatsby anyway. It might be that doing it dynamically on the client side makes more sense. I haven't used this WPGraphQLWoo with Gatsby yet so I'm not 100% sure though.

**Comment by kidunot89** [comment]
☝🏿 Agreed. I'm closing because it looks like there wasn't an issue here in the first place.
