### ISSUE TITLE
How to query a field added using add_post_type_support() function in Wordpress/Woocommerce?

### ISSUE THREAD

**Issue by arjunmurali1993** [wp-graphql/wp-graphql-woocommerce#443]
I have used the [add_post_type_support() function](https://developer.wordpress.org/reference/functions/add_post_type_support/) in my theme's functions.php file to add the standard Wordpress **author** field to Woocommerce Products (I run a multivendor store). 

I'm trying to query this field in order to display it in the front end that I'm building but since it isn't registered with wp-graphql, I'm getting the error _Cannot query type "author" on type "Product"_

Could you please help me in registering this author field for woocommerce products so that I can query the same using graphql?

**Comment by jacobarriola** [comment]
Hey @arjunmurali1993 !

That's odd that it doesn't show it because it seems like it should, per https://github.com/wp-graphql/wp-graphql/blob/develop/src/Connection/PostObjects.php#L229

Perhaps my logic is off, @jasonbahl ? 🤔 

In any event, I think you could add that `author` field to the GraphQL schema yourself. Have you looked into Connections with WPGraphQL and the `register_graphql_connection()` function?

It _could_ look something like this (not tested):

```php
use WPGraphQL\WooCommerce\Data\Connection\Product_Connection_Resolver;

add_action( 'graphql_register_types', function () {
  register_graphql_connection( [
		'fromType'       => 'User',
 		'toType'         => 'Product',
		'fromFieldName'  => 'author',
		 'resolve'       => function ( $source, $args, $context, $info ) {
 			$resolver = new Product_Connection_Resolver( $source, $args, $context, $info );
			
			$resolver->set_query_arg( 'author', $source->post_author );
			
			return $resolver->get_connection();
		},
	] );
}

```

The docs also have some examples of connections to look as a reference: https://www.wpgraphql.com/recipes/register-connection-to-attached-media/

**Comment by arjunmurali1993** [comment]
Thanks for the snippet @jacobarriola! I've added it to my theme's functions.php file but I'm not sure if it is working. 

I'm very new to this, so my apologies if I've missed something very basic or am looking at the wrong place for the data.

This is the graphql query I'm trying in the graphiql IDE:
```
query MyQuery {
  products(where: {orderby: {field: TOTAL_SALES}}, first: 12) {
    pageInfo {
      hasNextPage
      endCursor
    }
    nodes {
      name
      author
      databaseId
      slug
    }
  }
}
```
The author field is where I'm getting the _Cannot query type "author" on type "Product"_ error in graphiql IDE.

**Comment by kidunot89** [comment]
@arjunmurali1993 The Product post-type has a traditional `author` field already it's just not exposed because it's typically set to the superadmin. This field isn't available by default on the WC_Product object, but you could access your field on the WP_Post object for the product, you could add this field to `Product` interface using `register_graphql_field()`.

Here an example 

```php
register_graphql_field(
	'Product',
	'author',
	array(
		'type'        => 'User',
		'description' => __( 'Product Author', 'test-domain' ),
		'resolve'     =>
		function( \WPGraphQL\WooCommerce\Model\Product $source, array $args, AppContext $context ) {
			$post = $source->as_WP_Post();

			return \WPGraphQL\Data\DataSource::resolve_user( $post->post_author, $context );
		},
	)
);
```

I personally don't recommend doing this due to the risk of the super admin data getting exposed. Also note WPGraphQL's **User** model has checks in place to validate the end-user right to see User data.

**Comment by arjunmurali1993** [comment]
@kidunot89 I tried your code and it has added the author field to the Product query - exactly what I wanted. However, queries made to this author field are returning an internal server error on that line and the data shows `author: null`. Could you please help out with this?

I use a multivendor marketplace plugin ([this one](https://wordpress.org/plugins/wc-multivendor-marketplace/)), so instead of the super admin, each product gets assigned a vendor - which is basically the author field that is used for Posts. I checked inside the WP_POSTS table via phpmyadmin and post_author is indeed the field that stores the vendor user's id for products.
