### ISSUE TITLE
Is it abandoned?

### ISSUE THREAD

**Issue by topheroes** [wp-graphql/wp-graphql-woocommerce#496]
Hello,

No movements in this repository for a long time now. Is it abandoned?

**Comment by w3bdesign** [comment]
Likely not abandoned, but it's safe to say that development has been progressing slowly.

**Comment by w3bdesign** [comment]
The creator opened a pull request yesterday:

https://github.com/wp-graphql/wp-graphql-woocommerce/pull/497

**Comment by kidunot89** [comment]
@topheroes No, the project hasn't been abandoned. I've just had a lot less time to dedicate to maintain the project due to other responsibilities at my dayjob that have my time split across the WPGraphQL codebase, plus some other private codebases. 

Seriously, sorry about the slowed updates. I've got a big release coming up as soon as possible.
