### ISSUE TITLE
Internal Server Error : "Same value for "graphql_single_name" and "graphql_plural_name"..."

### ISSUE THREAD

**Issue by markwill890** [wp-graphql/wp-graphql-woocommerce#505]
When I enable the WooGraphQL I start seeing internal server errors, as follows...

The pa_delivered-as taxonomy cannot declare the same value for "graphql_single_name" and "graphql_plural_name"

After I activate the WooGraphQL plugin the GraphiQL plugin reports "No schema" (presumably because of the internal server error). Deactivating WooGraphQL resolves that issue.

**TO REPRODUCE**
1. Install and activate WPGraphQL (V1.3.98 used here), WPGraphiQL works fine at this point.
2. Install and activate WooGraphQL (V0.81 used)
3. Access WPGraphiQL - "No schema" displayed and the error message above written to debug log

**Expected behavior**
Both WordPress and WooCommerce scheme displayed and used in queries in WPGraphiQL

**Desktop (please complete the following information):**
 - OS: Windows 10 (all updates applied)
 - Chrome (all updates applied)

**Plugin Versions**
- **WooGraphQL Version:** 0.89
- **WPGraphQL Version:** 1.39
- **WordPress Version:** 5.7.2
- **WooCommerce Version:** 5.30

**Comment by akshaykatale99** [comment]
please check product attributes for the plural name. for me, I have an Album page attribute with album-pages slug. after changing slug album-pages to album-page and it worked.

**Comment by markwill890** [comment]
> please check product attributes for the plural name. for me, I have an Album page attribute with album-pages slug. after changing slug album-pages to album-page and it worked.

Thank you for the response. I did have a couple of attributes that happened to end in an 's' in the slug. I changed those but the problem remains.

**Comment by akshaykatale99** [comment]
You are getting the same error after changing attributes?

**Comment by akshaykatale99** [comment]
> > please check product attributes for the plural name. for me, I have an Album page attribute with album-pages slug. after changing slug album-pages to album-page and it worked.
> 
> Thank you for the response. I did have a couple of attributes that happened to end in an 's' in the slug. I changed those but the problem remains.

You are getting the same error after changing attributes?

**Comment by kidunot89** [comment]
@markwill890 @akshaykatale99 I'll be attempting to address this in the next minor release.

The current problems here are
- Use of an **Inflector** class to create the product attribute connection field name from the product attribute label. If this label is plural it will cause a duplicate type error.
- The **Inflector** class is also very simple and does not work for all words it seems.

The current plan is to introduce a naming convention.

```
single: AttributeName
plural: AttributeNameCollection
```

To avoid large logic rewrites in existing code developers can use GraphQL alias.
```graphql
query {
  paColor(id: "someId") {
    databaseId
  }
  paColors: paColorCollection {
    nodes {
      databaseId
    }
  }
}
```
@jacobarriola 👇🏿 You should join this because this would probably every you too.

Anyone have any objections to this? I'm very open to ideas on this matter.

_P.S. Another option would to be adding a GraphQL connection field name input field to the product attribute edit page, but I don't like this idea because it would add an extra layer of complexity on the product attributes queries and the logic would need to be made patched in the event of a collision with another plugin changing the edit page. 
Also seems like it would be a super unnecessary feature with GraphQL Aliases can be give the result field output whatever name desired._

**Comment by jacobarriola** [comment]
@kidunot89

> The current plan is to introduce a naming convention.
>
> single: AttributeName 
> plural: AttributeNameCollection

Naming is fine, especially with GraphQL aliases. My thoughts:

1. What's @jasonbahl doing on the core WPGraphQL side of things? I'd prefer parity with how the naming convention is going to be with core.
2. Let's make this filterable so that users have a choice to change the API as they see fit (ie maybe the prefer attributes to be called `allPaColors` instead)
