### ISSUE TITLE
Order shipping address not visible in wordpress admin panel

### ISSUE THREAD

**Issue by topheroes** [wp-graphql/wp-graphql-woocommerce#527]
When I log in
```

mutation LoginUser {
  login( input: {
    clientMutationId: "1214",
    username: "user@email.com",
    password: "nenado"
  } ) {
    authToken
    user {
      id
      name
    }
  }
}
```

Then add to card

```
mutation cartAdd{
  addToCart(input: { productId: 332, quantity: 2, clientMutationId: "1215" }){
    
    cartItem {
      quantity
      subtotal
      subtotalTax
      tax
      total
      key
    }
  }
}
```

Then checkout

```
mutation checkout{
    checkout( input:{clientMutationId:"1216",isPaid:false, shipping:{address2:"дом колотушкина", address1: "Улица Пушкина", email:"user@email.com", firstName:"Уася", lastName:"Пупкин", postcode:"244", state:"st", company:"dod", phone:"12892121", city:"hehe", country:RU}, paymentMethod:"cod"} ) {
        clientMutationId
         
    }
}
```

The order appears in wordpress admin Woocommerce Orders page, but it doesn't have the shipping address. 
Please advise.

**Comment by kidunot89** [comment]
@topheroes I think you forgot the `shipToDifferentAddress` flag. Try this.
```graphql
mutation checkout{
    checkout( input:{clientMutationId:"1216",isPaid:false, shipping:{address2:"дом колотушкина", address1: "Улица Пушкина", email:"user@email.com", firstName:"Уася", lastName:"Пупкин", postcode:"244", state:"st", company:"dod", phone:"12892121", city:"hehe", country:RU}, shipToDifferentAddress: true, paymentMethod:"cod"} ) {
        clientMutationId
         ...
    }
}
```

**Comment by topheroes** [comment]
@kidunot89 

`shipToDifferentAddress ` makes no difference, there is no shipping address shown in wordpress backend.

**Comment by JamieBradders** [comment]
Hey, I'm experiencing this issue too. Is there a suggested workaround to make this visible until the 0.11.0 milestone has been met? Thank you, P.S. I really appreciate the work that goes into the plugin 🙏

**Comment by JamieBradders** [comment]
Hey @topheroes I just noticed that I was experiencing this problem because a Shipping Zone was not set on my instance of WooCommerce 🤦. It might be worth checking your instance too, incase it is missing a shipping zone? 

Once I activated the shipping zone, I could see the shipping address appearing in the WooCommerce Admin Order screen.

**Comment by kidunot89** [comment]
@topheroes Any changes on this?

**Comment by plexus77** [comment]
Hi guys, I think I found the issue, on line 54 of the class-checkout-mutation.php

Seems that if either the ship_to_different_address or WC()->cart->needs_shipping_address() are false then the shipping fields are skipped, for some reason in my system WC()->cart->needs_shipping_address() is always false, perhaps because I have no shipping classes set...  though that has never caused issues in the past when the site was not headless.

Anyway there is filter that can be used to override the check so that it is always true.

 'woocommerce_cart_needs_shipping'
