### ISSUE TITLE
Adding composite product to cart

### ISSUE THREAD

**Issue by emre-koc** [wp-graphql/wp-graphql-woocommerce#556]
We are using [Composite products ](https://woocommerce.com/products/composite-products/) from woocommerce and we couldn't add composite product to cart with all component options. Is there anyone who can lead us right direction to how to add a composite product withh all component options to cart? 

Thanks a lot!

**Comment by emre-koc** [comment]
Hey @jacobarriola !

Thanks for your help. I was able to create addToCart mutation for composite product in graphql. I will create a PR request to original repo. 

Now I cannot get cart info from graphql for each composite product added. It lists composite product as a product and all components as a separate product in cart. How can I group products for each product composite product?

Thanks!

**Comment by jacobarriola** [comment]
@emre-koc  That's awesome! Nice work 👏

> I will create a PR request to original repo.

Not sure if it's worth the effort since composites is a 3rd-party add on. From afar, the philosphy seems to be to only support core WC and WP data and add support via a wp-graphql extension. See the list here: https://www.wpgraphql.com/extensions

You may want to simply open-source your work for everyone to use it!

> How can I group products for each product composite product?

Oooh. That's a tough one. I had to do something like that for bundles.

Specifically, I had to create a new connection on the `CartItem` type and called it `bundleContents`, which contained the bundle items for a given product bundle.

I also created a new field called `bundleParent` in `CartItem`, which returns a `Product` so that in my front end app I could filter out bundle items that have parents from appearing in the cart as standalone products.

I'll get a blog post out that documents this.

Connections docs: https://www.wpgraphql.com/docs/connections/

**Comment by brianpereradap** [comment]
> Hey @jacobarriola !
> 
> Thanks for your help. I was able to create addToCart mutation for composite product in graphql. I will create a PR request to original repo.
> 
> Now I cannot get cart info from graphql for each composite product added. It lists composite product as a product and all components as a separate product in cart. How can I group products for each product composite product?
> 
> Thanks!

@emre-koc were you able to get the composite products to work with the wp-graphql?
