### ISSUE TITLE
Question: Variations On Single Product Page

### ISSUE THREAD

**Issue by TheAggressive** [wp-graphql/wp-graphql-woocommerce#563]
Is there a way to query a variation like `Size: M Color: Black` as I have the variation(s) mapped on the single product page to select `size` and `color` as opposed to a dropdown that list variations like **_T-Shirt - Black, S_** | **_T-Shirt - Black, M_** | **_T-Shirt - Black, L_** ...etc...

But when a size or color is selected I feel I would need to send a query to update the price and product id of the variation matching those. I know you could map the following graphql query (below) but I'm not sure this is the most user friendly approach and could be potential to user error with selecting the wrong size or color of variation (they select the right color but wrong size because they read it wrong) 

```graphql
query Product {
  product(id: "1845", idType: DATABASE_ID) {
    ... on VariableProduct {
      id
      name
      variations {
        nodes {
          databaseId
          name
        }
      }
    }
  }
}
```

So again, looking for a way to select the size and color separately and fire of a query to find the matching product variation base on that and return the product id so that could be added to cart.

**Comment by jacobarriola** [comment]
Hey @TheAggressive !

You're correct (kind of 😄). On the Rudis app, I'm making a query to the API based on the attribute(s) selected; however, rather than querying my API to get a variation ID, my query is to:
1. get an inventory status based on a product id (variation ID if a variable product and product ID if a simple product)
2. get variation images

I'm getting all of the variations up front at *build time* (along with all of their attributes). Therefore, since I have all of that data client side, what I'm doing is determining the variation (and its ID) based on the attributes that a user *chooses*.

For instance, if a user chooses color:red and size:medium, because I have _all_ of the variations, I know that that combination of attributes is associated with one specific variation ID.

The tradeoff with this approach is that I have to ask for all the possible combinations at build time, but it also eliminates me having to make a bunch of run-time queries to get a variation ID.

**Comment by jacobarriola** [comment]
No problem. Assuming you have two attributes in your schema (color and size). I'm omitting the other fields for simplicity too.

```graphql
        ... on VariableProduct {
          regularPrice
          salePrice
          attributes {
            nodes {
              name
              options
              variation
              visible
            }
          }
          defaultAttributes {
            nodes {
              name
              attributeId
            }
          }
          variations(first: 100) {
            nodes {
              databaseId
              status
              regularPrice
              salePrice
              attributes {
                nodes {
                  attributeId
                  name
                  value
                }
              }
            }
          }
          paSizes(first: 100) {
            nodes {
              slug
              name
              termTaxonomyId
              taxonomy {
                node {
                  name
                }
              }
            }
          }
          paColors(first: 100) {
            nodes {
              slug
              name
              termTaxonomyId
              taxonomy {
                node {
                  name
                }
              }
            }
          }
        }
```

**Comment by TheAggressive** [comment]
Thank you @jacobarriola !

Working on building the function to check the variations based on the user selected options. Kinda difficult but I'll get it eventually!
