### ISSUE TITLE
Unknown argument "format" on field "WpSimpleProduct.price"

### ISSUE THREAD

**Issue by kdotamoh** [wp-graphql/wp-graphql-woocommerce#586]
**Describe the bug**
Adding the argument (format: RAW) to the `price` field throws an error.

**To Reproduce**
```
{
  allWpProduct {
    nodes {
      ... on WpSimpleProduct {
        name
        price(format: RAW)
        uri
        featuredImage {
          node {
            sourceUrl
          }
        }
      }
    }
  }
}
```

**Expected behavior**
Get price without currency symbol

**Screenshots**
<img width="921" alt="Screenshot 2021-12-09 at 3 52 58 AM" src="https://user-images.githubusercontent.com/21177558/145332071-2801b93b-a56f-4f1b-ad4c-f215aba274d0.png">

**Desktop (please complete the following information):**
 - OS: macOS Big sur 11.6
 - Browser: Chrome
 - Version: 95

**Plugin Versions**
- **WooGraphQL Version:** 0.10.6
- **WPGraphQL Version:** 1.6.10
- **WordPress Version:** 5.8.2
- **WooCommerce Version:** 5.9.0

**Additional context**
 I know this used to work in previous versions. Did something change that needs to be documented or is this a bug?

**Comment by kidunot89** [comment]
@kdotamoh This is most likely an issue with Gatsby. @TylerBarnes any ideas?

**Comment by TylerBarnes** [comment]
Due to the way Gatsby works, `gatsby-source-wordpress`'s schema isn't 1:1 with WPGraphQL's. Essentially Gatsby uses the WPGraphQL schema to build a brand new schema, querying data from WPGraphQL to use in this new schema. Field arguments aren't supported in Gatsby currently - this is possible but not a feature that's been implemented in source-wordpress.
