### ISSUE TITLE
Activation plugin failed

### ISSUE THREAD

**Issue by H-Nguyenx** [wp-graphql/wp-graphql-woocommerce#596]
**Describe the bug**
After successfully install the plugin version 0.10.6, when I try to activate the plugin. It created errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/33373945/148645148-b669ca6d-2fc0-467d-aa42-bb7dd213f7c5.png)

**Plugin Versions**
- **WooGraphQL Version:** 0.10.6
- **WPGraphQL Version:** 1.6.11
- **WordPress Version:** 5.8.1
- **WooCommerce Version:** 6.0.0

**Comment by abettermap** [comment]
@H-Nguyenx by any chance did you install the plugin using a zip of the full Git repo? I got the same error as you, in the same environment, but using [this zip](https://github.com/wp-graphql/wp-graphql-woocommerce/releases/download/v0.10.6/wp-graphql-woocommerce.zip) instead of the full source code worked:

![image](https://user-images.githubusercontent.com/4974087/148668118-73bd4eea-9dda-4644-852f-91e44bcd24ee.png)

So, the cause of the problem appears to be on me, but I think the "Getting Started" section of the docs could be clarified by adding something to the effect of "expand the Assets section and download the release, not the other zip" in this sentence:

> Clone or download the most stable release from the repository into your WordPress plugin directory & activate the plugin.

To be fair, I mistakenly downloaded the source from here, not the releases, so maybe it's an edge case and I'm just having a 🙃  moment:

![image](https://user-images.githubusercontent.com/4974087/148668264-b6709df3-9bcf-4250-a592-85e8ba799caa.png)

**Comment by H-Nguyenx** [comment]
> @H-Nguyenx by any chance did you install the plugin using a zip of the full Git repo? I got the same error as you, in the same environment, but using [this zip](https://github.com/wp-graphql/wp-graphql-woocommerce/releases/download/v0.10.6/wp-graphql-woocommerce.zip) instead of the full source code worked:
> 
> ![image](https://user-images.githubusercontent.com/4974087/148668118-73bd4eea-9dda-4644-852f-91e44bcd24ee.png)
> 
> So, the cause of the problem appears to be on me, but I think the "Getting Started" section of the docs could be clarified by adding something to the effect of "expand the Assets section and download the release, not the other zip" in this sentence:
> 
> > Clone or download the most stable release from the repository into your WordPress plugin directory & activate the plugin.
> 
> To be fair, I mistakenly downloaded the source from here, not the releases, so maybe it's an edge case and I'm just having a 🙃 moment:
> 
> ![image](https://user-images.githubusercontent.com/4974087/148668264-b6709df3-9bcf-4250-a592-85e8ba799caa.png)

Thank you very much, it fixs the problem!
