### ISSUE TITLE
Disable woocommerce-session header

### ISSUE THREAD

**Issue by samyrooster** [wp-graphql/wp-graphql-woocommerce#653]
Is there any option/hook to prevent sending `woocommerce-session` header response?

Because I disabled shopping/authentication on my website and I don't need this header anymore.

Also when using cache plugins (Litespeed cache WP) the exactly generated `woocommerce-session` for first visited user will be cached and send it to other anonymous users requests in next visit. It would be better to send this session from cookie instead of header, so it can be controlled on cache plugin to filter it.

**Comment by kidunot89** [comment]
Yes, just added this some where early on in your WP code `define( 'NO_QL_SESSION_HANDLER', true );`

**Comment by samyrooster** [comment]
Thanks but after adding `define( 'NO_QL_SESSION_HANDLER', true );` to `wp-config.php`, when I want to get the sessionToken through graphql request, it returns error.

```gql
{
  customer{
    sessionToken
  }
}
```
```json
    "errors": [
        {
            "debugMessage": "Call to undefined method WC_Session_Handler::build_token()",
            "message": "Internal server error",
            "extensions": {
                "category": "internal"
            },
            "locations": [
                {
                    "line": 1,
                    "column": 39
                }
            ],
            "path": [
                "customer",
                "sessionToken"
            ]
        }
    ],
```

**Comment by kidunot89** [comment]
@samyrooster That because the constant disable the custom session handler and reverts back to the default session handler. 

I see you just wanted to kill the `woocommerce-session` HTTP header, in that case you just have to remove [these two filters](https://github.com/wp-graphql/wp-graphql-woocommerce/blob/develop/includes/class-woocommerce-filters.php#L32-L33), and the code sample below should do the trick.
```php
remove_filter( 'graphql_response_headers_to_send', [ '\WPGraphQL\WooCommerce\WooCommerce_Filters', 'add_session_header_to_expose_headers' ] );
remove_filter( 'graphql_access_control_allow_headers', [ '\WPGraphQL\WooCommerce\WooCommerce_Filters', 'add_session_header_to_allow_headers' ] );
```

☝🏿 That should prevent WPGraphQL from exposing the header but the custom session handler will still be enabled.

**Comment by kidunot89** [comment]
@samyrooster Any updates on this?

**Comment by samyrooster** [comment]
Thanks, it worked well
