### ISSUE TITLE
Guests who use the same billing email can see each others orders in the customer object?

### ISSUE THREAD

**Issue by zaironjacobs** [wp-graphql/wp-graphql-woocommerce#818]
I create two different sessions for guests (not logged in).

I create a checkout for each, both of them with the same email for billing:
`
mutation {
    checkout(
        input: {
            paymentMethod: "stripe"
            shipping: {
                country: NL
                city: ""
                email: "johndoe@email.com"
                firstName: ""
                lastName: ""
                postcode: ""
                address1: ""
            }
            billing: {
                country: NL
                city: ""
                email: "johndoe@email.com"
                firstName: ""
                lastName: ""
                postcode: ""
                address1: ""
            }
            shippingMethod: ["free_shipping"]
            customerNote: ""
            isPaid: false
            transactionId: ""
        }
    ) {
        order {
            billing{
                email
            }
            id
            databaseId
            orderKey
            total
            subtotal
            lineItems {
                nodes {
                    databaseId
                    product {
                        node {
                            name
                        }
                    }
                }
            }
        }
        redirect
        result
    }
}
`

Then I fetch the customer like this:
`
    query GetCustomerQuery {
        customer {
            orders(first: 100) {
                nodes {
                    id
                    orderNumber
                }
            }
        }
    }
`

They can see each others orders.
Is this a bug or I'm not understanding something here?

Another thing is that I can't query the guest's own order like this:

`
query GetOrder {
  order(id: "...", idType: ID) {
    id
  }
}
`

It says  `Not authorized to access this order`.
But as mentioned previously, using the customer's object, I can get the order.

**Comment by kidunot89** [comment]
@zaironjacobs It's not a bug. That's just how most guest checkout system work.

It will always be assumed that both those guests are the same person shopping on two separate occasions, and they aren't getting another guest's order but an order from there last session 🤔. 

This assumption is made because two people can't legitimately have the same email address unless something is being spoofed 😅.

Also you'll find that authenticated user orders can't be accessed this way.

Lastly the `order` and `orders` queries are restricted to admin with `shop_manager`, and usage is recommended to be through a serverless function or the like authenticated through a token with a long life like a WordPress Application Password. 

The recommended way to access guest orders as follows

```graphql
query {
  customer {
    orders {
      nodes {
        ... order fields
      }
    }
  }
}
```

**Comment by zaironjacobs** [comment]
@kidunot89 Thanks for the clarification!
