### ISSUE TITLE
Customer id doesn't match user id

### ISSUE THREAD

**Issue by rotexhawk** [wp-graphql/wp-graphql-woocommerce#90]
I am using this plugin and the recommended woocommerce plugin. The problem is that `ids` don't match so when a user logs in I save their id and when they are ready to checkout I query for `customer(id: ID)` but the problem is that these id's don't match. If you provide the default db id's graphql complains. Shouldn't they share the same ids? 

Here is the result of the queries. 

```
"data": {
    "customers": {
      "nodes": [
        {
          "email": "test@test.com",
          "username": "test",
          "id": "Y3VzdG9tZXI6Mg==",
          "customerId": 2
        },
```

 ```
"users": {
      "nodes": [
        {
          "email": "test@test.com",
          "username": "test",
          "id": "dXNlcjoy",
          "userId": 2
        },
```

**Comment by kidunot89** [comment]
They don't match and this by design for both caching and object resolution. The *User* and *Customer* types are two different objects and should be used as such. Most, if not all, of the relative fields are accessible from the *Customer* type. If you need more fields from the *User* type, you have two options.
- Add them to the *Customer* type using filters.
- Run a second query using `userBy( userId: customerId )`. While the relay global IDs, a.k.a. `id` fields, are different on the two types, the `customerId` and `userId` are identical and can be use to query the the type using the `customerBy` and `userBy` queries.
